apiVersion: constraints.gatekeeper.sh/v1beta1
kind: validate-poddisruptionbudget
metadata:
  name: validate-poddisruptionbudget
spec:
  match:
    kinds:
    - apiGroups: ["policy"]
      kinds: [PodDisruptionBudget]
